before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 6.9.1
  - nvm use 6.9.1

install:
  - npm install

script:
  - npm test

notifications:
  email:
    recipients:
      - weiss@maxwellhealth.com
    on_success: change
    on_failure: change
